const V=1, STEP=50, SPEED=72, STORE='emberveil-coop-session-v1';
const $=id=>document.getElementById(id), lobby=$('lobby'), game=$('game'), canvas=$('canvas'), ctx=canvas.getContext('2d');
const keys=new Set(); let socket=null, snapshot=null, local=null, seq=0, attackSeq=0, lastInput=0, noticeUntil=0, reconnectTimer=0, reconnectAttempt=0, closing=false;
let predicted={x:44,y:90}, pending=[], remoteFrames=[], rtt=0, lastSnapshotAt=0;
const session=()=>{try{return JSON.parse(localStorage.getItem(STORE)||'null')}catch{return null}};
const saveSession=v=>v?localStorage.setItem(STORE,JSON.stringify(v)):localStorage.removeItem(STORE);
function send(type,payload,id){if(socket?.readyState===WebSocket.OPEN)socket.send(JSON.stringify({v:V,type,...(id?{id}:{}),payload}))}
function wsUrl(){return `${location.protocol==='https:'?'wss':'ws'}://${location.host}`}
function setStatus(t){$('status').textContent=t} function toast(t){$('notice').textContent=t;noticeUntil=performance.now()+2600}
function connect(operation,data){closing=false;setStatus('Connecting…');socket?.close();socket=new WebSocket(wsUrl());socket.addEventListener('open',()=>send('hello',{operation,clientVersion:'0.1.0',...data}));socket.addEventListener('message',e=>receive(e.data));socket.addEventListener('close',()=>{if(closing)return; toast('Connection lost. Reconnecting…');scheduleReconnect()});socket.addEventListener('error',()=>setStatus('Connection error'))}
function scheduleReconnect(){const s=session();if(!s){showLobby();return}clearTimeout(reconnectTimer);const delay=Math.min(5000,500*2**reconnectAttempt++);reconnectTimer=setTimeout(()=>connect('reconnect',{inviteCode:s.roomCode,playerId:s.playerId,reconnectToken:s.reconnectToken}),delay)}
function validObject(v){return v&&typeof v==='object'&&!Array.isArray(v)}
function validSnapshot(s){return validObject(s)&&typeof s.roomCode==='string'&&typeof s.localPlayerId==='string'&&Number.isFinite(s.serverTime)&&Array.isArray(s.players)&&validObject(s.world)&&validObject(s.shared)&&validObject(s.enemy)&&Array.isArray(s.projectiles)&&Array.isArray(s.pickups)&&s.players.every(p=>validObject(p)&&typeof p.id==='string'&&Number.isFinite(p.x)&&Number.isFinite(p.y)&&Number.isFinite(p.health))}
function receive(raw){let m;try{m=JSON.parse(raw)}catch{return}if(!validObject(m)||m.v!==V||typeof m.type!=='string'||!validObject(m.payload))return;
 if(m.type==='welcome'){if(!validSnapshot(m.payload.snapshot))return;const p=m.payload;saveSession({roomCode:p.roomCode,playerId:p.playerId,reconnectToken:p.reconnectToken});reconnectAttempt=0;showGame(p.roomCode);applySnapshot(p.snapshot,true);return}
 if(m.type==='snapshot'){if(validSnapshot(m.payload))applySnapshot(m.payload,false);return}
 if(m.type==='ping'){send('pong',{nonce:m.payload.nonce,clientTime:Date.now()});return}
 if(m.type==='error'){toast(m.payload.message||m.payload.code||'Server rejected message');if(!m.payload.recoverable){saveSession(null);showLobby()}return}
 if(m.type==='event')handleEvent(m.payload)}
function handleEvent(e){if(!validObject(e)||typeof e.eventType!=='string'||!validObject(e.payload))return;const p=e.payload;
 const text={ 'player-joined':`${p.displayName} joined`, 'player-reconnected':`${p.displayName} reconnected`, 'player-disconnected':`${p.displayName} disconnected`, 'switch-activated':'Shared switch activated', 'door-opened':'Sentinel door opened', 'enemy-defeated':'Veil Sentinel defeated', 'reward-granted':'Signal Shard granted to the room', 'player-downed':'A warden is down', 'player-revived':'Warden revived', 'pickup-collected':'Pickup secured' }[e.eventType];if(text)toast(text);if(e.eventType==='notice')toast(p.text||'')}
function showGame(code){lobby.hidden=true;game.hidden=false;$('room').textContent=code;requestAnimationFrame(frame)} function showLobby(){game.hidden=true;lobby.hidden=false;setStatus('Offline')}
function applySnapshot(s,first){const now=performance.now(),previous=snapshot;snapshot=s;lastSnapshotAt=now;local=s.players.find(p=>p.id===s.localPlayerId)||null;if(!local)return;
 rtt=local.rttMs||rtt;pending=pending.filter(i=>i.seq>local.lastProcessedInputSeq);const auth={x:local.x,y:local.y};predicted=first?auth:replay(auth,pending);if(Math.hypot(predicted.x-auth.x,predicted.y-auth.y)>45)predicted=auth;
 if(previous)remoteFrames.push({at:now-100,players:previous.players,enemy:previous.enemy,projectiles:previous.projectiles});remoteFrames.push({at:now,players:s.players,enemy:s.enemy,projectiles:s.projectiles});remoteFrames=remoteFrames.slice(-8);updateQuality()}
function replay(pos,inputs){let p={...pos};for(const i of inputs)p=movePredicted(p,i);return p}
function movePredicted(p,i){let x=i.moveX,y=i.moveY,len=Math.hypot(x,y);if(len>1){x/=len;y/=len}const d=SPEED*i.dt/1000,n={x:Math.max(11,Math.min(309,p.x+x*d)),y:Math.max(31,Math.min(169,p.y+y*d))},door=snapshot?.world?.door;if(door&&!door.open&&circleRect(n.x,p.y,7,door))n.x=p.x;if(door&&!door.open&&circleRect(n.x,n.y,7,door))n.y=p.y;return n}
function circleRect(x,y,r,o){const cx=Math.max(o.x,Math.min(x,o.x+o.width)),cy=Math.max(o.y,Math.min(y,o.y+o.height));return (x-cx)**2+(y-cy)**2<r*r}
function inputVector(){const x=(keys.has('ArrowRight')||keys.has('KeyD')?1:0)-(keys.has('ArrowLeft')||keys.has('KeyA')?1:0),y=(keys.has('ArrowDown')||keys.has('KeyS')?1:0)-(keys.has('ArrowUp')||keys.has('KeyW')?1:0);return{x,y}}
function facing(v){if(Math.abs(v.x)>Math.abs(v.y))return v.x<0?'left':'right';if(v.y)return v.y<0?'up':'down';return local?.facing||'right'}
function inputTick(now){if(!snapshot||!local||snapshot.cutscene.active||local.downed||now-lastInput<STEP)return;lastInput=now;const v=inputVector(),i={seq:++seq,dt:STEP,moveX:v.x,moveY:v.y,facing:facing(v)};pending.push(i);pending=pending.slice(-20);predicted=movePredicted(predicted,i);send('input',i)}
function nearestTarget(){if(!snapshot||!local)return null;const candidates=[{id:'shared-switch',...snapshot.world.switch},...snapshot.pickups.filter(p=>!p.collectedBy.includes(local.id)),{id:'major-reward',...snapshot.world.reward}];let best=null;for(const c of candidates){const d=Math.hypot(predicted.x-c.x,predicted.y-c.y);if(d<28&&(!best||d<best.d))best={id:c.id,d}}return best?.id||null}
function aim(){const v=inputVector();if(v.x||v.y){const l=Math.hypot(v.x,v.y);return{x:v.x/l,y:v.y/l}}return {up:{x:0,y:-1},down:{x:0,y:1},left:{x:-1,y:0},right:{x:1,y:0}}[local?.facing||'right']}
function attack(kind){const a=aim();send('attack',{clientAttackId:`${local?.id||'p'}:${++attackSeq}`,kind,aimX:a.x,aimY:a.y})}
function revive(active){const other=snapshot?.players.find(p=>p.id!==local?.id&&p.downed);if(other)send('revive',{targetPlayerId:other.id,active})}
function ping(){send('ping-marker',{x:predicted.x,y:predicted.y,kind:'look'})}
function emote(n){send('emote',{emote:['wave','cheer','help','thanks'][n-1]})}
addEventListener('keydown',e=>{keys.add(e.code);if(game.hidden)return;if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space'].includes(e.code))e.preventDefault();if(e.repeat)return;if(e.code==='KeyJ')attack('melee');if(e.code==='KeyK')attack('bolt');if(e.code==='KeyE'){const t=nearestTarget();if(t)send('interact',{targetId:t})}if(e.code==='KeyR')revive(true);if(e.code==='KeyP')ping();if(/^Digit[1-4]$/.test(e.code))emote(Number(e.code.at(-1)))});addEventListener('keyup',e=>{keys.delete(e.code);if(e.code==='KeyR')revive(false)});
function sampleRemote(id,now){const target=now-100;let a=remoteFrames[0],b=remoteFrames.at(-1);for(let i=1;i<remoteFrames.length;i++)if(remoteFrames[i].at>=target){a=remoteFrames[i-1];b=remoteFrames[i];break}const pa=a?.players.find(p=>p.id===id),pb=b?.players.find(p=>p.id===id)||pa;if(!pa||!pb)return pb;const t=Math.max(0,Math.min(1,(target-a.at)/Math.max(1,b.at-a.at)));return{...pb,x:pa.x+(pb.x-pa.x)*t,y:pa.y+(pb.y-pa.y)*t}}
function draw(now){ctx.imageSmoothingEnabled=false;ctx.setTransform(2,0,0,2,0,0);ctx.clearRect(0,0,320,180);ctx.fillStyle='#1d332b';ctx.fillRect(0,0,320,180);ctx.fillStyle='#29483a';for(let x=0;x<320;x+=16)for(let y=20;y<180;y+=16)if((x+y)%32===0)ctx.fillRect(x,y,16,16);if(!snapshot)return;
 const w=snapshot.world;ctx.fillStyle=w.switch.active?'#91e08b':'#b7a35a';ctx.fillRect(w.switch.x-6,w.switch.y-6,12,12);if(!w.door.open){ctx.fillStyle='#68535b';ctx.fillRect(w.door.x,w.door.y,w.door.width,w.door.height)}ctx.fillStyle='#e6c75e';ctx.fillRect(w.reward.x-5,w.reward.y-5,10,10);
 for(const p of snapshot.pickups)if(!p.collectedBy.includes(local.id)){ctx.fillStyle=p.kind==='currency'?'#f0d365':'#7ed8a2';ctx.fillRect(p.x-3,p.y-3,6,6)}
 if(snapshot.enemy.alive){ctx.fillStyle=snapshot.enemy.phase===1?'#9b4f67':'#d55b62';ctx.fillRect(snapshot.enemy.x-10,snapshot.enemy.y-10,20,20);ctx.fillStyle='#111';ctx.fillRect(snapshot.enemy.x-12,snapshot.enemy.y-17,24,4);ctx.fillStyle='#ef6b6b';ctx.fillRect(snapshot.enemy.x-12,snapshot.enemy.y-17,24*snapshot.enemy.health/snapshot.enemy.maxHealth,4)}
 for(const q of snapshot.projectiles){ctx.fillStyle=q.ownerType==='enemy'?'#e77c8d':'#8acbff';ctx.fillRect(q.x-2,q.y-2,4,4)}
 for(const p of snapshot.players){const r=p.id===local.id?{...p,...predicted}:sampleRemote(p.id,now)||p;ctx.fillStyle=p.id===local.id?'#e9f2b0':'#87b7dd';ctx.fillRect(r.x-6,r.y-6,12,12);if(p.downed){ctx.strokeStyle='#ff6a6a';ctx.strokeRect(r.x-8,r.y-8,16,16)}ctx.fillStyle='#fff';ctx.font='6px monospace';ctx.fillText(p.displayName,r.x-12,r.y-10)}
 ctx.fillStyle='#071014cc';ctx.fillRect(0,0,320,20);ctx.fillStyle='#fff';ctx.font='8px monospace';ctx.fillText(`HP ${local.health}/${local.maxHealth}  Glints ${local.inventory.currency}  Players ${snapshot.players.filter(p=>p.connected).length}/2`,6,13)}
function updateQuality(){const age=performance.now()-lastSnapshotAt,q=rtt<90&&age<400?'good':rtt<180&&age<900?'fair':'poor';$('quality').className=q;$('quality').textContent=`${q.toUpperCase()} · ${Math.round(rtt)} ms`}
function frame(now){if(game.hidden)return;inputTick(now);draw(now);if(now>noticeUntil)$('notice').textContent='';if(now-lastSnapshotAt>500)updateQuality();$('cutscene').hidden=!snapshot?.cutscene?.active;requestAnimationFrame(frame)}
$('create').onclick=()=>connect('create',{displayName:$('name').value||'Warden'});$('join').onclick=()=>connect('join',{displayName:$('name').value||'Warden',inviteCode:$('code').value.toUpperCase()});$('copy').onclick=async()=>{await navigator.clipboard?.writeText($('room').textContent);toast('Invite copied')};$('leave').onclick=()=>{closing=true;socket?.close();saveSession(null);showLobby()};$('ready').onclick=()=>snapshot&&send('cutscene-ready',{sequenceId:snapshot.cutscene.id,step:snapshot.cutscene.step});
const previous=session();if(previous)connect('reconnect',{inviteCode:previous.roomCode,playerId:previous.playerId,reconnectToken:previous.reconnectToken});
